"""Default contacts supplied in accounts.csv. Saved user edits take precedence."""

DEFAULT_LAWYER_CONTACTS = {
    "Oday Jaber Sihl": "lawyer9.bgd.iraq@intersos.org",
    "Dawlat Jumaah Ali": "lawyer3.kri.iraq@intersos.org",
    "Kosar Jabar Hama": "lawyer3.suli.iraq@intersos.org",
    "Nawf Khalid Talib": "hotlineparalegal2.bagdad.iraq@intersos.org",
    "Adnan Abdul-Latif Jassim": "hotlineparalegal.bagdad.iraq@intersos.org",
    "Zena Mohanad": "legaltl2.bgd.iraq@intersos.org",
    "Yousif Mahmood Salman": "lawyer8.bgd.iraq@intersos.org",
    "Hadeer Ali": "lawyer.missan.iraq@intersos.org",
    "Salih Hani": "lawyer.karbala.iraq@intersos.org",
    "Amer Ibrahim": "lawyer.sad.iraq@intersos.org",
    "Amer Sami": "legaltl1.bgd.iraq@intersos.org",
    "Raghad Isam": "lawyer7.bgd.iraq@intersos.org",
    "Samer Imad": "lawyer6.bgd.iraq@intersos.org",
    "Ruba Ahmed": "lawyer5.bgd.iraq@intersos.org",
    "Fuad Adel": "lawyer4.bgd.iraq@intersos.org",
    "Mustafa Naji": "lawyer3.bgd.iraq@intersos.org",
    "Ali Layth": "lawyer2.bgd.iraq@intersos.org",
    "Aymen Ibrahim Ismael": "lawyer1.bgd.iraq@intersos.org",
    "Zainab Abdulmajid": "lawyer.najaf.iraq@intersos.org",
    "Ayat Abdulkareem": "lawyer.basra.iraq@intersos.org",
    "Hadeel Akram": "lawyer.babil.iraq@intersos.org",
    "Mohammed Taha Abed": "lawyer.anbar.iraq@intersos.org",
    "Kamal Mustafa Jabbar": "lawyer.kirkuk.iraq@intersos.org",
    "Saad Ibrahim Arzooqi": "lawyer.mosul.iraq@intersos.org",
    "Eman Jawdat": "lawyer2.kri.iraq@intersos.org",
    "Warvin Mdhat Ahmed": "lawyer5.suli.iraq@intersos.org",
    "Ali Mohammed": "lawyer11.eastninewa.iraq@intersos.org",
    "Husam Salih": "lawyer10.eastninewa.iraq@intersos.org",
    "Raad Ali Ahmed": "lawyer9.eastninewa.iraq@intersos.org",
    "Hoshyar Salih Education": "education.suli.iraq@intersos.org",
    "Akram Abdulrahman": "lawyer8.eastninewa.iraq@intersos.org",
    "Koyar Mesoud Mahmood": "lawyer27.kri.iraq@intersos.org",
    "Hardi Safaaldin Kareem": "lawyer4.suli.iraq@intersos.org",
    "Hoshyar Salih": "north.manager.iraq@intersos.org",
    "Muhsen IM Assistant": "im.assistant.ninewa.iraq@intersos.org",
    "Sazan Ismail Fattah": "lawyer21.kri.iraq@intersos.org",
    "Suliman Ahmed Thyab": "lawyer1.eastninewa.iraq@intersos.org",
    "Fatima Abdulbasit": "lawyer6.eastninewa.iraq@intersos.org",
    "Younis Jamal Y": "im.meal.iraq@intersos.org",
    "Rebaz Fadhil": "lawyer10.kri.iraq@intersos.org",
    "Noor Ismail": "lawyer4.kri.iraq@intersos.org",
    "Hiwa Wiso": "lawyer9.kri.iraq@intersos.org",
    "Zahraa Jumaah": "legal.tl1.kri.iraq@intersos.org",
    "Rawiaa Abdulwahid": "legal.kri.iraq@intersos.org",
    "Falah Hassan": "legaltl1.eastninewa.iraq@intersos.org",
    "Karam Waad Muhammad Jasim": "lawyer2.eastninewa.iraq@intersos.org",
    "Zaid Wegaa Khader": "lawyer5.eastninewa.iraq@intersos.org",
    "Ahmad Mustafa Qassim": "baghdad.manager.iraq@intersos.org",
    "Ahmet Ibrahim": "protection.iraq@intersos.org"
}
