import {useEffect,useMemo,useState} from 'react';
import Plot from 'react-plotly.js';
import {Filter,LayoutDashboard,RotateCcw,Table2} from 'lucide-react';
import {getStudio} from './api';
import {AppSelect,ExportButtons,FilterDrawer,formatNumber,formatPercent} from './components';
import type {Filters,Measure,Metadata,StudioResult,Theme} from './types';

type ChartType='bar'|'stacked'|'line'|'donut'|'heatmap'|'table';
const ink=(t:Theme)=>t==='glass-dark'?'#edf7ff':'#263746';
const grid=(t:Theme)=>t==='glass-dark'?'rgba(190,215,232,.13)':'rgba(90,115,135,.13)';
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function Studio({metadata,theme}:{metadata:Metadata;theme:Theme}){
  const [source,setSource]=useState('assessment'),[row,setRow]=useState('project'),[column,setColumn]=useState(''),[measure,setMeasure]=useState<Measure>('records'),[chartType,setChartType]=useState<ChartType>('bar'),[filters,setFilters]=useState<Filters>({}),[drawer,setDrawer]=useState(false),[result,setResult]=useState<StudioResult|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[graph,setGraph]=useState<any>(null);
  const [customColors,setCustomColors]=useState(false),[markColors,setMarkColors]=useState<Record<string,string>>({}),[textColors,setTextColors]=useState<Record<string,string>>({});
  const sourceMeta=metadata.pages[source]; const dimensions=sourceMeta?.dimensions||Object.keys(sourceMeta?.filters||{}); const activeCount=Object.values(filters).reduce((n,v)=>n+v.length,0);
  useEffect(()=>{setFilters({});setColumn('');setMeasure('records');setRow(metadata.pages[source]?.dimensions?.[0]||'project')},[source,metadata]);
  useEffect(()=>{if(!row)return;const controller=new AbortController();setBusy(true);setError('');getStudio(source,row,column,filters,measure,controller.signal).then(setResult).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[source,row,column,filters,measure]);
  const colorKeys=useMemo(()=>{if(!result)return[];const columns=[...new Set(result.cells.map(c=>c.column))];return columns.length>1?columns:[...new Set(result.cells.map(c=>c.row))]},[result]);
  const chart=useMemo(()=>buildChart(result,chartType,theme,customColors?markColors:{},customColors?textColors:{}),[result,chartType,theme,customColors,markColors,textColors]);
  return <><div className="studio-toolbar glass"><div className="studio-heading"><LayoutDashboard/><div><strong>Analysis builder</strong><span>Choose a source, one or two dimensions, and a visual.</span></div></div><div className="studio-controls">
    <Select label="Source sheet" value={source} onChange={setSource} options={[['assessment','Assessments'],['services','Legal Services'],['deportation','Deportation']]}/>
    <Select label="Rows / X-axis" value={row} onChange={setRow} options={dimensions.map(d=>[d,label(d)])}/>
    <Select label="Columns / Series" value={column} onChange={setColumn} options={[['','None'],...dimensions.filter(d=>d!==row).map(d=>[d,label(d)] as [string,string])]}/>
    <Select label="Measure" value={measure} onChange={v=>setMeasure(v as Measure)} options={source==='deportation'?[['records','PN IDs']]:[['records',source==='services'?'Service IDs':'Assessment IDs'],['beneficiaries','Unique beneficiaries']]}/>
    <Select label="Output" value={chartType} onChange={v=>setChartType(v as ChartType)} options={[['bar','Ranked bar'],['stacked','Stacked bar'],['line','Line'],['donut','Donut'],['heatmap','Heatmap'],['table','Pivot table']]}/>
  </div><div className="studio-actions"><button className="primary" onClick={()=>setDrawer(true)}><Filter/>Filters {activeCount>0&&<b>{activeCount}</b>}</button><button className="soft" onClick={()=>setFilters({})}><RotateCcw/>Clear filters</button></div>{theme==='multicolor'&&chartType!=='table'&&<section className="studio-color-panel"><div className="studio-color-head"><div><strong>Answer colors</strong><span>Use the curated palette or customize chart and label colors independently.</span></div><label className="color-toggle"><input type="checkbox" checked={customColors} onChange={e=>setCustomColors(e.target.checked)}/><i/><span>Custom colors</span></label></div>{customColors&&<div className="studio-color-grid">{colorKeys.map((key,index)=><div className="answer-color" key={key}><span title={key}>{key}</span><label>Chart<input type="color" value={markColors[key]||palette[index%palette.length]} onChange={e=>setMarkColors(colors=>({...colors,[key]:e.target.value}))}/></label><label>Text<input type="color" value={textColors[key]||defaultText[index%defaultText.length]} onChange={e=>setTextColors(colors=>({...colors,[key]:e.target.value}))}/></label></div>)}</div>}</section>}</div>
  {error&&<div className="error glass">{error}</div>}
  <article className="studio-canvas glass"><div className="card-title"><div><h3>{label(row)}{column?` by ${label(column)}`:''}</h3><p>{result?`${formatNumber(result.total)} filtered ${measure==='beneficiaries'?'beneficiaries':'records'} · 2026 YTD`:''}</p></div><div className="chart-actions">{chartType!=='table'&&<ExportButtons graph={graph} title={`${label(row)}${column?` by ${label(column)}`:''}`}/>}<span className="studio-badge"><Table2/>{chartType==='table'?'Pivot':'Interactive chart'}</span></div></div>{busy&&!result?<div className="loading"><div/><span>Building analysis…</span></div>:chartType==='table'?<StudioTable result={result}/>:chart&&<div className="studio-plot"><Plot key={`${source}-${row}-${column}-${chartType}-${theme}`} useResizeHandler onInitialized={(_,gd)=>setGraph(gd)} data={chart.data as any} layout={chart.layout as any} config={{displayModeBar:false,responsive:true,scrollZoom:false,doubleClick:false}} style={{width:'100%',height:'100%'}}/></div>}</article>
  <FilterDrawer open={drawer} available={sourceMeta?.filters||{}} filters={filters} onClose={()=>setDrawer(false)} onChange={setFilters} onReset={()=>setFilters({})}/></>
}

function Select({label:caption,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <AppSelect label={caption} value={value} onChange={onChange} options={options as [string,string][]}/>}

const palette=['#315ea8','#2f8f68','#d4852f','#7759b8','#c94f68','#16858d','#9b6b35','#526d8d'];
const defaultText=['#ffffff','#ffffff','#172334','#ffffff','#ffffff','#ffffff','#ffffff','#ffffff'];
function buildChart(result:StudioResult|null,type:ChartType,theme:Theme,marks:Record<string,string>,texts:Record<string,string>){if(!result||!result.cells.length)return null;const rows=[...new Set(result.cells.map(c=>c.row))],cols=[...new Set(result.cells.map(c=>c.column))],cell=(r:string,c:string)=>result.cells.find(x=>x.row===r&&x.column===c)?.count||0;const common={autosize:true,height:560,margin:{l:90,r:35,t:35,b:90},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{family:'DM Sans,Segoe UI,sans-serif',color:ink(theme)},dragmode:false,uirevision:'studio',xaxis:{gridcolor:grid(theme),fixedrange:true,automargin:true},yaxis:{gridcolor:grid(theme),fixedrange:true,automargin:true},legend:{orientation:'h',y:1.08},showlegend:cols.length>1};if(type==='heatmap'&&cols.length>1)return{data:[{type:'heatmap',x:cols,y:rows,z:rows.map(r=>cols.map(c=>cell(r,c))),colorscale:[[0,'#edf2fb'],[1,marks[cols[0]]||'#315ea8']],hovertemplate:'%{y}<br>%{x}: %{z:,.0f}<extra></extra>'}],layout:common};if(type==='donut'&&cols.length===1)return{data:[{type:'pie',labels:rows,values:rows.map(r=>cell(r,cols[0])),hole:.58,textinfo:'label+percent',marker:{colors:rows.map((r,i)=>marks[r]||palette[i%palette.length])},textfont:{color:rows.map((r,i)=>texts[r]||defaultText[i%defaultText.length])},hovertemplate:'%{label}<br>%{value:,.0f} · %{percent}<extra></extra>'}],layout:{...common,margin:{l:30,r:30,t:30,b:30},showlegend:false}};const traces=cols.map((c,i)=>{const single=cols.length===1;const values=rows.map(r=>cell(r,c));return{type:type==='line'?'scatter':'bar',mode:type==='line'?'lines+markers+text':undefined,name:c,x:rows,y:values,text:type==='line'?values.map(formatNumber):undefined,textposition:type==='line'?'top center':undefined,marker:{color:single?rows.map((r,j)=>marks[r]||palette[j%palette.length]):marks[c]||palette[i%palette.length]},line:{width:3,color:marks[c]||palette[i%palette.length]},textfont:{color:single?rows.map((r,j)=>texts[r]||defaultText[j%defaultText.length]):texts[c]||defaultText[i%defaultText.length]},hovertemplate:`%{x}<br>${c}: %{y:,.0f}<extra></extra>`}});return{data:traces,layout:{...common,barmode:type==='stacked'?'stack':'group'}}}

function StudioTable({result}:{result:StudioResult|null}){if(!result)return null;const rows=[...new Set(result.cells.map(c=>c.row))],cols=[...new Set(result.cells.map(c=>c.column))];return <div className="table-wrap studio-table"><table><thead><tr><th>{label(result.rowDimension)}</th>{cols.map(c=><th key={c}>{c}</th>)}<th>Total</th></tr></thead><tbody>{rows.map(r=>{const cells=cols.map(c=>result.cells.find(x=>x.row===r&&x.column===c));const total=cells.reduce((n,x)=>n+(x?.count||0),0);return <tr key={r}><td>{r}</td>{cells.map((x,i)=><td key={cols[i]}>{x?`${formatNumber(x.count)} · ${formatPercent(x.percent)}`:'—'}</td>)}<td><strong>{formatNumber(total)}</strong></td></tr>})}</tbody></table></div>}
