/* Run against a local Vite server with the bundled Playwright module. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||"playwright");
const assert=require("node:assert/strict");
const fs=require("node:fs");
(async()=>{
  const browser=await chromium.launch({executablePath:process.env.EDGE_PATH||"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",headless:true});
  const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
  page.on("pageerror",error=>errors.push(String(error)));
  await page.goto((process.env.APP_TEST_URL||"http://127.0.0.1:5174")+"/performance-harness.html");
  await page.getByRole("button",{name:"All options",exact:true}).click();
  const options=page.locator(".checkbox-multi-menu input[type=checkbox]");
  await options.first().waitFor();
  assert((await options.count())<100,"Dropdown rendered too many options");
  await options.first().check();
  assert.equal(await page.getByTestId("selection").textContent(),"Option 0000");
  const optionRoot=page.locator(".checkbox-multi-menu > div");
  await optionRoot.evaluate(node=>{node.scrollTop=node.scrollHeight});
  await page.getByText("Option 1999",{exact:true}).waitFor();
  const bottomScroll=await optionRoot.evaluate(node=>node.scrollTop);
  await page.getByRole("checkbox",{name:"Option 1999",exact:true}).check();
  await page.waitForTimeout(200);
  assert(Math.abs(await optionRoot.evaluate(node=>node.scrollTop)-bottomScroll)<2,"Checking an option reset the filter scroll");
  await page.getByRole("checkbox",{name:"Option 1999",exact:true}).uncheck();
  assert(Math.abs(await optionRoot.evaluate(node=>node.scrollTop)-bottomScroll)<2,"Unchecking an option reset the filter scroll");
  await page.getByText("Option 1999",{exact:true}).locator("..").locator("input").focus();
  await page.keyboard.press("Home");
  await page.waitForFunction(()=>document.activeElement?.closest("label")?.textContent==="Option 0000");
  await page.keyboard.press("End");
  await page.waitForFunction(()=>document.activeElement?.closest("label")?.textContent==="Option 1999");
  await page.keyboard.press("Space");
  assert.equal(await page.getByTestId("selection").textContent(),"Option 0000,Option 1999");
  await page.getByPlaceholder("Search options").fill("0123");
  assert.equal(await options.count(),1);
  await options.first().check();
  assert((await page.getByTestId("selection").textContent()).includes("Option 0123"));
  await page.locator(".filter-option-row").filter({has:page.getByRole("checkbox",{name:"Option 0123",exact:true})}).hover();
  await page.getByRole("button",{name:"Exclude Option 0123",exact:true}).click();
  const selectedValues=(await page.getByTestId("selection").textContent()).split(",");
  assert.equal(selectedValues.length,1999,"Exclude did not select offscreen options");
  assert(!selectedValues.includes("Option 0123"));
  assert.equal(await options.first().isChecked(),false);
  await page.getByPlaceholder("Search options").fill("");
  await optionRoot.evaluate(node=>{node.scrollTop=node.scrollHeight});
  await page.getByRole("checkbox",{name:"Option 1999",exact:true}).waitFor();
  const exclusionScroll=await optionRoot.evaluate(node=>node.scrollTop);
  await page.locator(".filter-option-row").filter({has:page.getByRole("checkbox",{name:"Option 1999",exact:true})}).hover();
  await page.getByRole("button",{name:"Exclude Option 1999",exact:true}).click();
  await page.waitForTimeout(200);
  assert(Math.abs(await optionRoot.evaluate(node=>node.scrollTop)-exclusionScroll)<2,"Exclude reset the filter scroll");
  assert.equal(await page.getByRole("checkbox",{name:"Option 1999",exact:true}).isChecked(),false);
  await page.getByRole("button",{name:"Done",exact:true}).click();
  const table=page.getByTestId("windowed-table");
  assert((await table.locator("tbody tr[data-window-index]").count())<100,"Table rendered too many rows");
  await table.evaluate(node=>{node.scrollTop=node.scrollHeight});
  await table.getByText("1999",{exact:true}).waitFor();
  assert((await table.locator("tbody tr[data-window-index]").count())<100);
  assert.equal(await page.getByTestId("all-records").textContent(),"2000");
  await page.getByRole("textbox",{name:"Result search"}).fill("Synthetic row 1234 ");
  await table.getByText("1234",{exact:true}).waitFor();
  assert.equal(await page.getByTestId("all-records").textContent(),"1");
  assert.equal(await table.locator("tbody tr[data-window-index]").count(),1);
  assert.deepEqual(errors,[]);
  const result={options:2000,records:2000,bounded_rendering:true,variable_heights:true,keyboard_home_end:true,selection_retained:true,search_offscreen:true,complete_data_retained:true,page_errors:errors};
  fs.writeFileSync(process.env.UI_RESULTS_PATH||"output/performance/windowed-lists.json",JSON.stringify(result,null,2));
  console.log(JSON.stringify(result));await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
